### PR TITLE
Update README and add contributing docs

### PR DESCRIPTION
**Pull request by MFHellscapes**
## About this merge request

This contains changes to the README in a separate branch due to branch protection policies in GitHub.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Community-Lores/awesome-neurodiversity/1)

### CODE REVIEW

**Review by ajhalili2006 — COMMENTED** [review]
While I might be committing stuff via my multifandom account due to some reasons that I'll explain later, I enabled branch protection on the `main` branch in case I start giving active contributors write access (`developer` level in GitLab, this is a bit complicated on sourcehut side) and to do one of the best practices in Git branching.

> *[Reviewable](https://reviewable.io/reviews/Community-Lores/awesome-neurodiversity/1#-:-NTfpBez4HkYzPFdESik:b-gx4k4y)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @MFHellscapes)

**Review by ajhalili2006 — COMMENTED** [review]
A bit of LGTM to me, but I'll due to by April 25 on GitHub.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Community-Lores/awesome-neurodiversity/1#-:-NTfqA1F6av-11Tgc5yg:bru5xqp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MFHellscapes)

**Review by MFHellscapes — COMMENTED** [review]
Gonna do a bit of final touches before I mark it off for final review. (from @ajhalili2006)

> *[Reviewable](https://reviewable.io/reviews/Community-Lores/awesome-neurodiversity/1#-:-NTnatKk1hdjQ4dCNQt3:borqy9u)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @ajhalili2006 and @MFHellscapes)

**Comment by MFHellscapes** [comment]
_Final review stage triggered on behalf of @ajhalili2006, as he now finalizes the performance task for Science 10._

**Review by ajhalili2006 — APPROVED** [review]
:lgtm_strong: Ready to merge at anytime.

> Reviewed 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/community-lores/awesome-neurodiversity/1#-:-NTnu30w-021hEBE2pnX:b-6h0o1n)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MFHellscapes)

**Review by MFHellscapes — COMMENTED** [review]
Onto it!

> *[Reviewable](https://reviewable.io/reviews/community-lores/awesome-neurodiversity/1#-:-NTnuHUIDm1ewQITK5ck:b6nhw51)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MFHellscapes)

**Pull request merged**
